export const ORDERS = [
  {
    id: '1',
    orderNumber: 'OO50778955',
    status: 'Shipped',
    orderedAt: 'March 21, 2026',
    shipDate: 'March 25, 2026',
    poNumber: '—',
    total: 779.70,
    onlineOrder: '—',
    orderType: 'Blank Order',
  },
  {
    id: '2',
    orderNumber: 'OO43331216',
    status: 'Shipped',
    orderedAt: 'March 9, 2026',
    shipDate: 'March 12, 2026',
    poNumber: '—',
    total: 355.96,
    onlineOrder: '—',
    orderType: 'Blank Order',
  },
  {
    id: '3',
    orderNumber: 'OO41256890',
    status: 'Processing',
    orderedAt: 'April 2, 2026',
    shipDate: '—',
    poNumber: 'PO-9921',
    total: 1120.00,
    onlineOrder: 'Yes',
    orderType: 'Custom Sublimation',
  },
  {
    id: '4',
    orderNumber: 'OO38714520',
    status: 'Pending',
    orderedAt: 'April 5, 2026',
    shipDate: '—',
    poNumber: '—',
    total: 245.50,
    onlineOrder: '—',
    orderType: 'Blank Order',
  },
  {
    id: '5',
    orderNumber: 'OO29871034',
    status: 'Cancelled',
    orderedAt: 'February 18, 2026',
    shipDate: '—',
    poNumber: 'PO-8844',
    total: 612.30,
    onlineOrder: 'Yes',
    orderType: 'Club Package',
  },
]

export const STATUS_COLORS = {
  Shipped: 'text-green-600',
  Processing: 'text-blue-500',
  Pending: 'text-amber-500',
  Cancelled: 'text-red-500',
}
