const routes = {
  home: "/",
  catalogues: "/catalogues",
  sportsCatalogue: "/sports-catalogue",
  headwearCatalogue: "/headwear-catalogue",
  apparelCatalogue: "/apparel-catalogue",
  brandCatalogues: "/catalogues/brand/:brandSlug",
  brandCatalogue: (brandSlug = ":brandSlug") =>
    `/catalogues/brand/${brandSlug}`,
  dashboard: "/dashboard",
  clubStore: "/club-store",
  account: "/account",
  orders: "/orders",
  support: "/support",
  freestyleSublimation: "/freestyle-sublimation",
  artLibrary: "/art-library",
  freestyleHeadwear: "/freestyle-headwear",
  freestyleDigitalPrint: "/freestyle-digital-print",
  supportTickets: "/support-tickets",
  accountUsers: "/account-users",
  savedCards: "/saved-cards",
  shippingAddresses: "/shipping-addresses",
  security: "/security",
  comingSoon: "/coming-soon",
  graphicRequest: "/graphic-request",
  faq: "/faq",
  announcements: "/announcements",
  orderForm: "/order-form",
  createLookBook: "/create-look-book",
};

export default routes;
